Repository Const-Project/MainFE, pull requests merged in 2025-08, with the labels that each got.

#22 [Chore] 모바일 웹앱 레이아웃 세팅 및 네브바 구현
  index.html
  src/App.tsx
  src/assets/icons/common/Xmack.svg
  src/assets/icons/common/bookmark1.svg
  src/assets/icons/common/bookmark2.svg
  src/assets/icons/common/calendar1.svg
  src/assets/icons/common/calendar2.svg
  src/assets/icons/common/camera.svg
  src/assets/icons/common/chat.svg
  src/assets/icons/common/edit.svg
  src/assets/icons/common/heart.svg
  src/assets/icons/common/home1.svg
  src/assets/icons/common/home2.svg
  src/assets/icons/common/index.ts
  src/assets/icons/common/left.svg
  src/assets/icons/common/level0.svg
  src/assets/icons/common/level1.svg
  src/assets/icons/common/level2.svg
  src/assets/icons/common/level3.svg
  src/assets/icons/common/right.svg
  src/assets/icons/common/search1.svg
  src/assets/icons/common/search2.svg
  src/assets/icons/common/user1.svg
  src/assets/icons/common/user2.svg
  src/components/QueryTest.tsx
  src/components/layout/Layout.tsx
  src/components/layout/LayoutWithoutNavbar.tsx
  src/components/layout/Navbar.tsx
  src/main.tsx
  src/pages/home/Homepage.tsx
  src/pages/log/LogPage.tsx
  src/pages/option/OptionPage.tsx
  src/pages/search/SearchPage.tsx
  src/styles/globals.css
  vite.config.ts
Labels: ✨Feature, 📌Chore

#26 [Feat] 일기쓰기 UI 구현
  src/App.tsx
  src/assets/icons/Check.svg
  src/assets/icons/Check2.svg
  src/assets/icons/common/Check.svg
  src/assets/icons/common/Check2.svg
  src/components/dailyMission/writeDiary/DiaryEditor.tsx
  src/components/dailyMission/writeDiary/DiaryFooter.tsx
  src/components/dailyMission/writeDiary/DiaryHeader.tsx
  src/components/dailyMission/writeDiary/ImageUploader.tsx
  src/pages/dailyMission/WriteDiaryPage.tsx
  src/styles/globals.css
  tsconfig.tsbuildinfo
Labels: ✨Feature, 🎨Design

#29 [Feat] 아바타 선택하기 UI 구현
  .pnp.cjs
  package.json
  src/components/registration/selectionFlow/SelectionDetail.tsx
  src/pages/registration/SelectionDetailPage.tsx
  src/routes/registrationRoutes.tsx
  yarn.lock
Labels: ✨Feature, 🎨Design

#33 [Feat] 일일미션_사진찍기 UI 구현
  src/App.tsx
  src/components/dailyMission/takePhoto/TakePhotoFooter.tsx
  src/components/dailyMission/takePhoto/TakePhotoMain.tsx
  src/pages/dailyMission/TakePhotoPage.tsx
Labels: ✨Feature, 🎨Design

#35 [Fix] Selection-Detail Page UI 수정
  src/components/common/Button.tsx
  src/components/registration/avatarCreation/AvatarCreationOption.tsx
  src/components/registration/avatarCreation/AvatarSelectionOption.tsx
  src/components/registration/selectionFlow/SelectionDetail.tsx
  src/pages/registration/AvatarCreationPage.tsx
  src/pages/registration/CreationDetailPage.tsx
  src/pages/registration/PlantNicknamePage.tsx
  src/pages/registration/SelectionDetailPage.tsx
  src/stores/avatarCreationStore.ts
Labels: ✨Feature, 🎨Design

#47 [Feat] 홈페이지, 온보딩 페이지
  .pnp.cjs
  index.html
  package.json
  src/App.tsx
  src/apis/instance.ts
  src/apis/register/registerApi.ts
  src/assets/icons/common/character.png
  src/assets/images/background/background1.png
  src/assets/images/background/background2.png
  src/assets/images/background/background3.png
  src/assets/images/background/background4.png
  src/assets/images/bird.png
  src/assets/images/bottom-sheet/clearFour.svg
  src/assets/images/bottom-sheet/clearOne.svg
  src/assets/images/bottom-sheet/clearThree.svg
  src/assets/images/bottom-sheet/clearTwo.svg
  src/assets/images/bottom-sheet/four.svg
  src/assets/images/bottom-sheet/one.svg
  src/assets/images/bottom-sheet/three.svg
  src/assets/images/bottom-sheet/two.svg
  src/assets/images/char.png
  src/assets/images/char2.png
  src/assets/images/character.png
  src/assets/images/map.png
  src/assets/images/map/map1.png
  src/assets/images/map/map2.png
  src/assets/images/map/map3.png
  src/assets/images/map/map4.png
  src/assets/images/onboarding/onboarding1.png
  src/assets/images/onboarding/onboarding2.png
  src/assets/images/onboarding/onboarding3.png
  src/assets/images/onboarding/onboarding4.png
  src/assets/images/onboarding/splash.png
  src/assets/images/plant.png
  src/components/bottom-sheet/BottomSheet.tsx
  src/components/common/Map.tsx
  src/components/common/Splash.tsx
  src/components/home/Avatar.tsx
  src/components/home/FirstPlant.tsx
  src/components/home/FourthPlant.tsx
  src/components/home/Modal.tsx
  src/components/home/SecondPlant.tsx
  src/components/home/ThirdPlant.tsx
  src/components/layout/Navbar.tsx
  src/components/loading/loading.tsx
  src/components/lock/Lock.tsx
  src/components/lock/UnLock.tsx
  src/components/map/Modal.tsx
  src/pages/home/Homepage.tsx
  src/pages/register/RegisterPage.tsx
  src/pages/splash/OnBoardingPage.tsx
  src/pages/splash/SplashPage.tsx
  src/stores/useTokenStore.ts
  src/styles/globals.css
  src/styles/home/swiper.css
  src/styles/swiper.css
  src/types/apis/register.ts
  vite.config.ts
  yarn.lock
Labels: ✨Feature, 🎨Design

#60 [Feat] 둘러보기, 아바타 상세, 설정 페이지 UI
  public/log/avatar1.png
  public/log/avatar2.png
  src/App.tsx
  src/assets/icons/common/index.ts
  src/assets/icons/common/togle1.svg
  src/assets/icons/common/togle2.svg
  src/assets/icons/common/userPlus.svg
  src/components/feed/FeedDetail.tsx
  src/components/feed/FeedList.tsx
  src/components/follow/UserCard.tsx
  src/components/layout/Navbar.tsx
  src/components/log/LogCalendar.tsx
  src/components/log/MyDiary.tsx
  src/mocks/feed/detail.ts
  src/mocks/feed/feed.ts
  src/mocks/follow/follow.ts
  src/pages/feed/FeedAvatarPage.tsx
  src/pages/feed/FeedDiaryPage.tsx
  src/pages/feed/FeedPage.tsx
  src/pages/follow/FollowPage.tsx
  src/pages/log/LogPage.tsx
  src/pages/option/OptionPage.tsx
  src/pages/search/SearchPage.tsx
  src/styles/fonts.css
  src/types/feed/detail.ts
  src/types/feed/index.ts
  src/types/follow/index.ts
  vite.config.ts
Labels: ✨Feature, 🎨Design

#62 [Refactor] 키움일지 / 둘러보기 API 연결
  src/App.tsx
  src/apis/feed/avatarPostDetailApi.ts
  src/apis/feed/feedApi.ts
  src/apis/follow/followApi.ts
  src/apis/log/calendarApi.ts
  src/apis/log/diariesApi.ts
  src/apis/log/diaryDetailApi.ts
  src/components/feed/FeedList.tsx
  src/components/log/LogCalendar.tsx
  src/components/log/MyDiary.tsx
  src/hooks/feed/useAvatarPostDetailApi.ts
  src/hooks/feed/useFeedApi.ts
  src/hooks/follow/useFollowApi.ts
  src/hooks/log/useCalendarApi.ts
  src/hooks/log/useDiariesApi.ts
  src/hooks/log/useDiaryDetailApi.ts
  src/mocks/feed/feed.ts
  src/mocks/log/monthlyCalendar.ts
  src/pages/feed/FeedAvatarPage.tsx
  src/pages/feed/FeedDiaryPage.tsx
  src/pages/feed/FeedPage.tsx
  src/pages/follow/FollowPage.tsx
  src/pages/log/LogDetailPage.tsx
  src/pages/log/LogPage.tsx
  src/pages/profile/ProfilePage.tsx
  src/types/feed/avatarPostDetailApi.type.ts
  src/types/feed/feedApi.type.ts
  src/types/log/calendarApi.type.ts
  src/types/log/diariesApi.type.ts
  src/types/log/diaryDetailApi.type.ts
Labels: ♻️Refactor

#78 [Feat] 아바타 생성하기 UI 구현 -MOCK
  src/assets/mocks/berry.svg
  src/components/registration/avatarCreation/AvatarCreationOption.tsx
  tsconfig.tsbuildinfo
Labels: ♻️Refactor

#80 [Fix] 사진 디바이스 접근 및 아바타 생성 페이지에서 나풀나풀 이름 띄우기
  src/components/registration/avatarCreation/AvatarCreationOption.tsx
  src/pages/registration/CreationDetailPage.tsx
  tsconfig.tsbuildinfo
Labels: 🐛Fix, ♻️Refactor
